import type { RevisionLeverDefinition, AIMarker, DocumentSignal } from "./types.js";

export const METRIC_LEVERS: Record<string, string[]> = {
  word_count: ["add_more_content", "trim_excess_content"],
  avg_words_per_sentence: ["shorten_long_sentences"],
  max_words_per_sentence: ["shorten_long_sentences", "break_sentence_tails"],
  sentence_length_p90: ["break_sentence_tails", "shorten_long_sentences"],
  sentence_length_p95: ["break_sentence_tails", "shorten_long_sentences"],
  percent_sentences_over_20_words: ["shorten_long_sentences"],
  percent_sentences_over_25_words: ["shorten_long_sentences"],
  percent_sentences_over_30_words: ["shorten_long_sentences", "break_sentence_tails"],
  percent_sentences_over_40_words: ["break_sentence_tails"],
  avg_words_per_paragraph: ["split_oversized_paragraphs"],
  max_words_per_paragraph: ["split_oversized_paragraphs"],
  paragraph_length_p90: ["split_oversized_paragraphs"],
  paragraph_length_p95: ["split_oversized_paragraphs"],
  percent_paragraphs_over_75_words: ["split_oversized_paragraphs"],
  percent_paragraphs_over_100_words: ["split_oversized_paragraphs"],
  percent_paragraphs_over_150_words: ["split_oversized_paragraphs"],
  lexical_diversity_ttr: ["reduce_repetition"],
  lexical_diversity_mattr: ["reduce_repetition"],
  repetition_ratio: ["reduce_repetition"],
  avg_characters_per_word: ["reduce_complex_word_density", "replace_difficult_words"],
  avg_syllables_per_word: ["reduce_complex_word_density"],
  long_word_ratio: ["reduce_complex_word_density"],
  difficult_word_ratio: ["replace_difficult_words"],
  complex_word_ratio: ["reduce_complex_word_density"],
  heading_density: ["increase_heading_frequency"],
  list_density: ["introduce_lists_for_scannability"],
  words_between_breaks: ["add_breaks_to_dense_sections"],
  paragraph_scannability_score: ["split_oversized_paragraphs", "introduce_lists_for_scannability"],
  sentence_tail_risk_score: ["break_sentence_tails"],
  dialogue_ratio: ["improve_dialogue_balance"],
  scene_density_proxy: ["tighten_scene_pacing"],
  exposition_density_proxy: ["tighten_scene_pacing"],
  sensory_term_density: ["ground_with_sensory_details"],
  abstract_word_ratio: ["reduce_abstract_wording"],
  flesch_reading_ease: ["shorten_long_sentences", "replace_difficult_words"],
  flesch_kincaid_grade_level: ["shorten_long_sentences", "replace_difficult_words"],
  gunning_fog: ["shorten_long_sentences", "reduce_complex_word_density"],
  smog: ["reduce_complex_word_density"],
  coleman_liau: ["shorten_long_sentences", "reduce_complex_word_density"],
  automated_readability_index: ["shorten_long_sentences", "reduce_complex_word_density"],
  dale_chall: ["replace_difficult_words", "shorten_long_sentences"],
  linsear_write: ["shorten_long_sentences", "reduce_complex_word_density"],
  type_token_ratio: ["reduce_repetition"],
  consensus_grade: ["shorten_long_sentences", "replace_difficult_words"],
};

export const METRIC_FORMULAS: Record<string, string[]> = {
  avg_words_per_sentence: ["flesch_reading_ease", "flesch_kincaid_grade_level", "gunning_fog", "automated_readability_index", "linsear_write"],
  max_words_per_sentence: ["flesch_reading_ease", "flesch_kincaid_grade_level", "gunning_fog", "automated_readability_index"],
  sentence_length_p90: ["flesch_kincaid_grade_level", "gunning_fog"],
  sentence_length_p95: ["flesch_kincaid_grade_level", "gunning_fog"],
  avg_characters_per_word: ["automated_readability_index", "coleman_liau"],
  avg_syllables_per_word: ["flesch_reading_ease", "flesch_kincaid_grade_level"],
  long_word_ratio: ["automated_readability_index", "coleman_liau"],
  complex_word_ratio: ["gunning_fog", "smog", "linsear_write"],
  difficult_word_ratio: ["dale_chall"],
  flesch_reading_ease: ["flesch_reading_ease"],
  flesch_kincaid_grade_level: ["flesch_kincaid_grade_level"],
  gunning_fog: ["gunning_fog"],
  smog: ["smog"],
  coleman_liau: ["coleman_liau"],
  automated_readability_index: ["automated_readability_index"],
  dale_chall: ["dale_chall"],
  linsear_write: ["linsear_write"],
  type_token_ratio: ["type_token_ratio"],
  consensus_grade: ["flesch_kincaid_grade_level", "gunning_fog", "smog", "coleman_liau", "automated_readability_index", "dale_chall", "linsear_write"],
};

export const REVISION_LEVER_CATALOG: Record<string, RevisionLeverDefinition> = {
  add_more_content: {
    label: "Add more content",
    description: "Expand the draft so it clears the requested minimum length.",
    effort: "medium",
    ease_score: 0.55,
    affected_metrics: ["word_count"],
    affected_formulas: [],
  },
  trim_excess_content: {
    label: "Trim excess content",
    description: "Cut redundant material so the draft fits the requested length target.",
    effort: "medium",
    ease_score: 0.65,
    affected_metrics: ["word_count"],
    affected_formulas: [],
  },
  shorten_long_sentences: {
    label: "Shorten long sentences",
    description: "Split or simplify long sentences to reduce global sentence-length pressure.",
    effort: "low",
    ease_score: 0.95,
    affected_metrics: ["avg_words_per_sentence", "max_words_per_sentence", "percent_sentences_over_20_words", "percent_sentences_over_30_words"],
    affected_formulas: ["flesch_reading_ease", "flesch_kincaid_grade_level", "gunning_fog", "dale_chall", "automated_readability_index", "linsear_write"],
  },
  split_oversized_paragraphs: {
    label: "Split oversized paragraphs",
    description: "Break dense paragraphs into smaller blocks to improve scan-ability.",
    effort: "low",
    ease_score: 0.85,
    affected_metrics: ["max_words_per_paragraph", "percent_paragraphs_over_100_words", "paragraph_length_p90"],
    affected_formulas: [],
  },
  replace_difficult_words: {
    label: "Replace difficult words",
    description: "Swap unfamiliar vocabulary for more common alternatives when meaning allows.",
    effort: "medium",
    ease_score: 0.8,
    affected_metrics: ["difficult_word_ratio", "difficult_word_count"],
    affected_formulas: ["dale_chall", "flesch_reading_ease", "flesch_kincaid_grade_level", "gunning_fog"],
  },
  reduce_complex_word_density: {
    label: "Reduce complex-word density",
    description: "Lower the share of long, multi-syllable words that inflate grade-level formulas.",
    effort: "medium",
    ease_score: 0.9,
    affected_metrics: ["complex_word_ratio", "avg_syllables_per_word", "avg_characters_per_word", "polysyllable_count"],
    affected_formulas: ["flesch_reading_ease", "flesch_kincaid_grade_level", "gunning_fog", "smog", "linsear_write", "automated_readability_index"],
  },
  reduce_repetition: {
    label: "Reduce repetition",
    description: "Vary repeated wording so the text feels less repetitive and less mechanically dense.",
    effort: "medium",
    ease_score: 0.7,
    affected_metrics: ["lexical_diversity_ttr", "repetition_ratio"],
    affected_formulas: ["type_token_ratio"],
  },
  add_breaks_to_dense_sections: {
    label: "Add breaks to dense sections",
    description: "Use headings, bullets, or paragraph breaks to reduce wall-of-text sections.",
    effort: "low",
    ease_score: 0.8,
    affected_metrics: ["max_words_per_paragraph", "percent_paragraphs_over_100_words", "heading_count", "list_item_count"],
    affected_formulas: [],
  },
  break_sentence_tails: {
    label: "Break sentence tails",
    description: "Shorten sentences that are weighted toward the end with excessive clauses.",
    effort: "low",
    ease_score: 0.9,
    affected_metrics: ["sentence_length_p90", "max_words_per_sentence"],
    affected_formulas: ["flesch_kincaid_grade_level", "gunning_fog"],
  },
  increase_heading_frequency: {
    label: "Increase heading frequency",
    description: "Add descriptive headings to improve navigational ease and break up long sections.",
    effort: "low",
    ease_score: 0.85,
    affected_metrics: ["heading_density", "words_per_heading"],
    affected_formulas: [],
  },
  introduce_lists_for_scannability: {
    label: "Introduce lists for scannability",
    description: "Convert dense comma-separated sequences or paragraphs into bulleted lists.",
    effort: "low",
    ease_score: 0.8,
    affected_metrics: ["list_density", "list_item_count", "paragraph_scannability_score"],
    affected_formulas: [],
  },
  reduce_abstract_wording: {
    label: "Reduce abstract wording",
    description: "Swap vague concepts for concrete, sensory, or grounded terms.",
    effort: "medium",
    ease_score: 0.6,
    affected_metrics: ["abstract_word_ratio", "sensory_term_density"],
    affected_formulas: [],
  },
  improve_dialogue_balance: {
    label: "Improve dialogue balance",
    description: "Add or trim dialogue to reach the desired narrative balance vs narration.",
    effort: "medium",
    ease_score: 0.7,
    affected_metrics: ["dialogue_ratio", "narration_vs_dialogue_balance"],
    affected_formulas: [],
  },
  tighten_scene_pacing: {
    label: "Tighten scene pacing",
    description: "Shorten sentences and paragraphs to increase the perceived speed of a scene.",
    effort: "medium",
    ease_score: 0.75,
    affected_metrics: ["avg_words_per_sentence", "avg_words_per_paragraph", "scene_density_proxy"],
    affected_formulas: ["flesch_reading_ease", "gunning_fog"],
  },
  ground_with_sensory_details: {
    label: "Ground with sensory details",
    description: "Incorporate more visual, auditory, or tactile terms to improve narrative immersion.",
    effort: "medium",
    ease_score: 0.65,
    affected_metrics: ["sensory_term_density"],
    affected_formulas: [],
  },
  reduce_targeted_word_usage: {
    label: "Reduce targeted word usage",
    description: "Remove or replace specific words or phrases that exceed the requested limits.",
    effort: "low",
    ease_score: 0.9,
    affected_metrics: [],
    affected_formulas: [],
  },
};

export const AI_MARKERS: AIMarker[] = [
  // 1. Lexical Markers - High Signal
  { pattern: "delve", category: "vocabulary", severity: "high" },
  { pattern: "underscore", category: "vocabulary", severity: "medium" },
  { pattern: "tapestry", category: "vocabulary", severity: "high" },
  { pattern: "realm", category: "vocabulary", severity: "high" },
  { pattern: "intricate", category: "vocabulary", severity: "medium" },
  { pattern: "meticulous", category: "vocabulary", severity: "medium" },
  { pattern: "pivotal", category: "vocabulary", severity: "medium" },
  { pattern: "robust", category: "vocabulary", severity: "low" },
  { pattern: "seamless", category: "vocabulary", severity: "low" },
  { pattern: "elevate", category: "vocabulary", severity: "low" },
  { pattern: "leverage", category: "vocabulary", severity: "low" },
  { pattern: "harness", category: "vocabulary", severity: "low" },
  { pattern: "unlock", category: "vocabulary", severity: "low" },
  { pattern: "empower", category: "vocabulary", severity: "low" },
  { pattern: "foster", category: "vocabulary", severity: "low" },
  { pattern: "navigate", category: "vocabulary", severity: "low" },
  { pattern: "streamline", category: "vocabulary", severity: "low" },
  { pattern: "transformative", category: "vocabulary", severity: "medium" },
  { pattern: "dynamic", category: "vocabulary", severity: "low" },
  { pattern: "holistic", category: "vocabulary", severity: "medium" },
  { pattern: "nuanced", category: "vocabulary", severity: "medium" },
  { pattern: "multifaceted", category: "vocabulary", severity: "medium" },
  { pattern: "comprehensive", category: "vocabulary", severity: "low" },
  { pattern: "crucial", category: "vocabulary", severity: "low" },
  { pattern: "essential", category: "vocabulary", severity: "low" },
  { pattern: "vital", category: "vocabulary", severity: "low" },
  { pattern: "noteworthy", category: "vocabulary", severity: "medium" },
  { pattern: "compelling", category: "vocabulary", severity: "low" },
  { pattern: "innovative", category: "vocabulary", severity: "low" },
  { pattern: "cutting-edge", category: "vocabulary", severity: "low" },
  { pattern: "game-changing", category: "vocabulary", severity: "low" },
  { pattern: "scalable", category: "vocabulary", severity: "low" },
  { pattern: "actionable", category: "vocabulary", severity: "low" },
  { pattern: "impactful", category: "vocabulary", severity: "low" },
  { pattern: "meaningful", category: "vocabulary", severity: "low" },
  { pattern: "commendable", category: "vocabulary", severity: "medium" },
  { pattern: "meticulously", category: "vocabulary", severity: "medium" },
  { pattern: "showcase", category: "vocabulary", severity: "low" },
  { pattern: "surpass", category: "vocabulary", severity: "low" },
  { pattern: "bolster", category: "vocabulary", severity: "low" },
  { pattern: "elucidate", category: "vocabulary", severity: "medium" },
  { pattern: "illuminate", category: "vocabulary", severity: "medium" },
  { pattern: "resonate", category: "vocabulary", severity: "low" },
  { pattern: "reimagine", category: "vocabulary", severity: "medium" },
  { pattern: "revolutionize", category: "vocabulary", severity: "medium" },
  { pattern: "encapsulate", category: "vocabulary", severity: "medium" },

  // AI Adverbs
  { pattern: "notably", category: "vocabulary", severity: "low" },
  { pattern: "importantly", category: "vocabulary", severity: "low" },
  { pattern: "significantly", category: "vocabulary", severity: "low" },
  { pattern: "increasingly", category: "vocabulary", severity: "low" },
  { pattern: "effectively", category: "vocabulary", severity: "low" },
  { pattern: "fundamentally", category: "vocabulary", severity: "low" },
  { pattern: "effortlessly", category: "vocabulary", severity: "low" },
  { pattern: "thoughtfully", category: "vocabulary", severity: "low" },
  { pattern: "strategically", category: "vocabulary", severity: "low" },

  // 2. Stock Phrases
  { pattern: "In today's digital landscape", category: "stock_phrases", severity: "high" },
  { pattern: "In an increasingly complex world", category: "stock_phrases", severity: "high" },
  { pattern: "As technology continues to evolve", category: "stock_phrases", severity: "high" },
  { pattern: "Whether you're a beginner or an expert", category: "stock_phrases", severity: "medium" },
  { pattern: "Now more than ever", category: "stock_phrases", severity: "medium" },
  { pattern: "The key takeaway is", category: "stock_phrases", severity: "medium" },
  { pattern: "take your workflow to the next level", category: "stock_phrases", severity: "high" },
  { pattern: "built for modern teams", category: "stock_phrases", severity: "medium" },
  { pattern: "all-in-one solution", category: "stock_phrases", severity: "medium" },
  { pattern: "without the hassle", category: "stock_phrases", severity: "medium" },
  { pattern: "in minutes, not hours", category: "stock_phrases", severity: "medium" },

  // 3. Sentence Patterns
  { pattern: "not only * but also", category: "sentence_patterns", severity: "medium" },
  { pattern: "it is not just about * it is about", category: "sentence_patterns", severity: "high" },
  { pattern: "while * is important, * is equally", category: "sentence_patterns", severity: "medium" },
  { pattern: "plays a crucial role in", category: "sentence_patterns", severity: "medium" },
  { pattern: "helps you save time and reduce complexity", category: "sentence_patterns", severity: "high" },
  { pattern: "built for developers who need speed and reliability", category: "sentence_patterns", severity: "high" },

  { pattern: "Ultimately", category: "stock_phrases", severity: "low" },
  { pattern: "At the end of the day", category: "stock_phrases", severity: "medium" },
  { pattern: "Let's dive in", category: "stock_phrases", severity: "medium" },
  { pattern: "Let's unpack this", category: "stock_phrases", severity: "medium" },
  { pattern: "In conclusion", category: "stock_phrases", severity: "medium" },
  { pattern: "To sum up", category: "stock_phrases", severity: "medium" },

  // 6. Generic Benefit Claims
  { pattern: "improve efficiency", category: "generic_claims", severity: "medium" },
  { pattern: "reduce complexity", category: "generic_claims", severity: "medium" },
  { pattern: "enhance productivity", category: "generic_claims", severity: "medium" },
  { pattern: "drive growth", category: "generic_claims", severity: "medium" },
  { pattern: "unlock value", category: "generic_claims", severity: "medium" },
  { pattern: "make better decisions", category: "generic_claims", severity: "medium" },
  { pattern: "build trust", category: "generic_claims", severity: "medium" },
  { pattern: "create a seamless experience", category: "generic_claims", severity: "medium" },

  // 4. Assistant Residue
  { pattern: "Certainly!", category: "assistant_residue", severity: "high" },
  { pattern: "Of course", category: "assistant_residue", severity: "medium" },
  { pattern: "As an AI language model", category: "assistant_residue", severity: "high" },
  { pattern: "I hope this helps", category: "assistant_residue", severity: "high" },
  { pattern: "Based on your request", category: "assistant_residue", severity: "medium" },
  { pattern: "Here is the rewritten version", category: "assistant_residue", severity: "high" },

  // 5. Stylistic Markers (Low signal alone, but count in density)
  { pattern: "—", category: "style_marker", severity: "low" },
];
export const AI_PATTERNS = AI_MARKERS;

export const DOCUMENT_SIGNALS: DocumentSignal[] = [
  {
    id: "specificity_deficit",
    name: "Specificity Deficit",
    category: "specificity_deficit",
    severity: "medium",
    explanation: "Low density of numbers or data points relative to word count. AI often generalizes without providing concrete evidence."
  },
  {
    id: "ai_skeleton",
    name: "AI Skeleton",
    category: "structural_pattern",
    severity: "medium",
    explanation: "Use of predictable article structures (Introduction -> Benefits -> Conclusion) typical of default assistant output."
  },
  {
    id: "paragraph_symmetry",
    name: "Paragraph Symmetry",
    category: "structural_pattern",
    severity: "medium",
    explanation: "Highly uniform paragraph lengths (e.g., all 3-5 sentences) which can feel mechanical."
  },
  {
    id: "repeated_starts",
    name: "Repeated Sentence Starts",
    category: "repetition_pattern",
    severity: "medium",
    explanation: "Multiple sentences starting with identical transitional phrases like 'This helps' or 'It provides'."
  },
  {
    id: "bold_leadins",
    name: "Bold Lead-ins",
    category: "punctuation_pattern",
    severity: "medium",
    explanation: "Excessive use of bolded terms followed by colons at the start of paragraphs or list items."
  },
  {
    id: "triads",
    name: "Triads",
    category: "triad_pattern",
    severity: "low",
    explanation: "Frequent use of 'Rule of Three' phrasing (A, B, and C) which is common in persuasive AI writing."
  }
];
